name: Linux CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          profile: minimal
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: make test
      - run: make fix
      - run: git diff HEAD --exit-code --color
